In [1]:
#Dependencies
import pandas as pd
from sqlalchemy import create_engine
import requests

In [2]:
#Extract CSV into DataFrame from movies
movies_file = "../OutputData/movies.csv"
movies_df = pd.read_csv(movies_file)
movies_df

,imdb_id,title,year,rated,released,runtime,genre,director,writer,actors,language,country,imdb_rating,type
0,tt0381707,White Chicks,2004,PG-13,23 Jun 2004,109 min,"Comedy, Crime",Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Marlon Wayans","Marlon Wayans, Shawn Wayans, Busy Philipps",English,United States,5.6,movie
1,tt0425210,Lucky Number Slevin,2006,R,07 Apr 2006,110 min,"Crime, Drama, Thriller",Paul McGuigan,Jason Smilovic,"Josh Hartnett, Ben Kingsley, Morgan Freeman",English,"United States, Germany, United Kingdom, Canada",7.7,movie
2,tt0413573,Grey's Anatomy,2005–,TV-14,27 Mar 2005,41 min,"Drama, Romance",NaN,Shonda Rhimes,"Ellen Pompeo, Chandra Wilson, James Pickens Jr.",English,United States,7.5,series
3,tt0455275,Prison Break,2005–2017,TV-14,29 Aug 2005,44 min,"Action, Crime, Drama",NaN,Paul T. Scheuring,"Dominic Purcell, Wentworth Miller, Amaury Nolasco","English, Arabic, Spanish","United Kingdom, United States",8.3,series
4,tt0460649,How I Met Your Mother,2005–2014,TV-14,19 Sep 2005,22 min,"Comedy, Romance",NaN,"Carter Bays, Craig Thomas","Josh Radnor, Jason Segel, Cobie Smulders","English, Persian, Chinese",United States,8.3,series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512,tt6878820,Z-O-M-B-I-E-S,2018,TV-G,16 Feb 2018,94 min,"Family, Musical, Romance",Paul Hoen,"David Light, Joseph Raso, David Light (based o...","Milo Manheim, Meg Donnelly, Trevor Tordjman, K...",English,United States,6.3,movie
1513,tt3544734,Zapped,2014,TV-G,23 Jun 2014,102 min,"Comedy, Family, Fantasy",Peter DeLuise,"Leslie Margolis (based on the novel ""Boys Are ...","Zendaya, Chanelle Peloso, Spencer Boldman, Emi...",English,"Canada, USA",5.1,movie
1514,tt0186726,Zenon: Girl of the 21st Century,1999,TV-G,23 Jan 1999,97 min,"Adventure, Comedy, Family, Sci-Fi",Kenneth Johnson,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Raven-Symoné, Stuart Pankin, H...",English,United States,6.4,movie
1515,tt0271271,Zenon: The Zequel,2001,TV-G,12 Jan 2001,100 min,"Comedy, Family, Adventure, Sci-Fi",Manny Coto,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Shadia Simmons, Lauren Maltby,...",English,"USA, New Zealand",5.9,movie
1516,tt0379060,Zenon: Z3,2004,TV-G,11 Jun 2004,81 min,"Adventure, Comedy, Family, Sci-Fi",Steve Rash,"Marilyn Sadler (character from the book ""Zenon...","Kirsten Storms, Lauren Maltby, Alyson Morgan, ...",English,United States,5.5,movie

In [3]:
#setting the index to imdb_id
movies_df.set_index("imdb_id", inplace=True)

movies_df.head()

,title,year,rated,released,runtime,genre,director,writer,actors,language,country,imdb_rating,type
imdb_id,,,,,,,,,,,,,
tt0381707,White Chicks,2004,PG-13,23 Jun 2004,109 min,"Comedy, Crime",Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Marlon Wayans","Marlon Wayans, Shawn Wayans, Busy Philipps",English,United States,5.6,movie
tt0425210,Lucky Number Slevin,2006,R,07 Apr 2006,110 min,"Crime, Drama, Thriller",Paul McGuigan,Jason Smilovic,"Josh Hartnett, Ben Kingsley, Morgan Freeman",English,"United States, Germany, United Kingdom, Canada",7.7,movie
tt0413573,Grey's Anatomy,2005–,TV-14,27 Mar 2005,41 min,"Drama, Romance",NaN,Shonda Rhimes,"Ellen Pompeo, Chandra Wilson, James Pickens Jr.",English,United States,7.5,series
tt0455275,Prison Break,2005–2017,TV-14,29 Aug 2005,44 min,"Action, Crime, Drama",NaN,Paul T. Scheuring,"Dominic Purcell, Wentworth Miller, Amaury Nolasco","English, Arabic, Spanish","United Kingdom, United States",8.3,series
tt0460649,How I Met Your Mother,2005–2014,TV-14,19 Sep 2005,22 min,"Comedy, Romance",NaN,"Carter Bays, Craig Thomas","Josh Radnor, Jason Segel, Cobie Smulders","English, Persian, Chinese",United States,8.3,series

In [19]:
#Extract CSV into DataFrame
platform_file = "../OutputData/platform.csv"
platform_df = pd.read_csv(platform_file)
platform_df

  platform_id platform_name
0         P01       Netflix
1         P02   Disney Plus
2         P03       Crackle

In [20]:
#setting the index to platform_id
platform_df.set_index("platform_id", inplace=True)

platform_df.head()

            platform_name
platform_id
P01               Netflix
P02           Disney Plus
P03               Crackle

In [6]:
#Create Database connection
connection_string = "postgres:postgres@localhost:5432/movies_db"
engine = create_engine(f'postgresql://{connection_string}')

In [7]:
# Confirm tables
engine.table_names()

/var/folders/s3/_tx_vh_n3jxcv5xmm_5v0lpr0000gn/T/ipykernel_18945/3015872754.py:2: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['moviesandshows', 'moviesource', 'source_table']

In [ ]:
#Use pandas to Load  csv converted DataFrames into database
movies_df.to_sql(name='movieandshows', con=engine, if_exists='append', index=True)

In [15]:
#confirm data has been added by quering the table
pd.read_sql_query('select * from moviesandshows', con=engine).head()

,imdb_id,title,year,rated,released,runtime,genre,director,writer,actors,language,country,imdb_rating,type
0,tt0381707,White Chicks,2004,PG-13,23 Jun 2004,109 min,"Comedy, Crime",Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Marlon Wayans","Marlon Wayans, Shawn Wayans, Busy Philipps",English,United States,5.6,movie
1,tt0425210,Lucky Number Slevin,2006,R,07 Apr 2006,110 min,"Crime, Drama, Thriller",Paul McGuigan,Jason Smilovic,"Josh Hartnett, Ben Kingsley, Morgan Freeman",English,"United States, Germany, United Kingdom, Canada",7.7,movie
2,tt0413573,Grey's Anatomy,2005–,TV-14,27 Mar 2005,41 min,"Drama, Romance",None,Shonda Rhimes,"Ellen Pompeo, Chandra Wilson, James Pickens Jr.",English,United States,7.5,series
3,tt0455275,Prison Break,2005–2017,TV-14,29 Aug 2005,44 min,"Action, Crime, Drama",None,Paul T. Scheuring,"Dominic Purcell, Wentworth Miller, Amaury Nolasco","English, Arabic, Spanish","United Kingdom, United States",8.3,series
4,tt0460649,How I Met Your Mother,2005–2014,TV-14,19 Sep 2005,22 min,"Comedy, Romance",None,"Carter Bays, Craig Thomas","Josh Radnor, Jason Segel, Cobie Smulders","English, Persian, Chinese",United States,8.3,series

In [ ]:
#Use pandas to Load  csv converted DataFrames into database
platform_df.to_sql(name='source_table', con=engine, if_exists='append', index=True)

In [16]:
#confirm data has been added by quering the table
pd.read_sql_query('select * from source_table', con=engine).head()

  platform_id platform_name
0         P01       Netflix
1         P02   Disney Plus
2         P03       Crackle